services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: abcde123
      POSTGRES_DB: mind
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8999:8080"

volumes:
  db-data: